### PR TITLE
Add Dockerfile. Fixes #44.

### LINKED ISSUE #44: Add Dockerfile to make the build process more easy, secure, and hermetic
This issue is relevant to all BlockchainCommons tools.
The current build process requires installing llvm 10 (and possibly other dependencies in the future), which requires build privileges and is not always desirable. In addition, building is not hermetic, it can be affected be anything already installed on the build machine.
A better approach, both in terms of build reproduciblity and user friendliness, is providing a Dockerfile and/or using a build system such as Bazel.

### PR DESCRIPTION
**Pull request by secinthenet**

### CODE REVIEW

**Comment by gorazdko** [comment]
(nit: add git dependency to Dockerfile, otherwise clone recursively)

tested ACK

**Comment by ChristopherA** [comment]
@wolfmcnally would you review this PR?

**Review by wolfmcnally — APPROVED** [review]
LGTM

**Comment by wolfmcnally** [comment]
@secinthenet This repo doesn't allow merging unsigned commits. Please resubmit this PR with a signed commit.

**Pull request closed without merging**
