### PR TITLE
Add Dockerfile. Fixes #44.

### LINKED ISSUE #44: Add Dockerfile to make the build process more easy, secure, and hermetic
This issue is relevant to all BlockchainCommons tools.
The current build process requires installing llvm 10 (and possibly other dependencies in the future), which requires build privileges and is not always desirable. In addition, building is not hermetic, it can be affected be anything already installed on the build machine.
A better approach, both in terms of build reproduciblity and user friendliness, is providing a Dockerfile and/or using a build system such as Bazel.

### PR DESCRIPTION
**Pull request by secinthenet**
Continuation of a previous PR #47

### CODE REVIEW

**Comment by gorazdko** [comment]
Thanks for the PR. Looks good to me, will test it today.

I'm not sure why linter suddenly decided to throw an error here as it is classified as style:

```bash
19/20 files checked 92% done
Checking utils.cpp ...
utils.cpp:135:21: style: Condition 'c==separator' is always true [knownConditionTrueFalse]
        } else if(c == separator && buf.length() > 0) {
                    ^
utils.cpp:133:8: note: Assuming condition 'c!=separator' is false
  if(c != separator) {
       ^
utils.cpp:135:21: note: Condition 'c==separator' is always true
        } else if(c == separator && buf.length() > 0) {
                    ^
20/20 files checked 100% done

```

And on linux:

```bash
12/20 files checked 60% done
Checking format-sskr.cpp ...
[format-sskr.cpp:45]: (error) Memory leak: bytes_buf
13/20 files checked 65% done
```

which is a false positive imo.

Anyways, the linter problems are on our side not caused by your PRs.

**Comment by gorazdko** [comment]
I have build and tested. Works fine.

shunit2 is introduced as a submodule now which i'm fine with, it's just a dev dependency

@ChristopherA  I think we can merge this in despite the linter failing. I'll reapply the linter fix subsequently. Also let me know if we want to document shunit2 as a *dev dependency* (reason is #55) to our README, and i'll add that too

**Review by ChristopherA — APPROVED** [review]

**Comment by ChristopherA** [comment]
Merging PR despite lint errors — @gorazdko will fix in subsequent PR so @secinthenet doesnt have to rebase.

@secinthenet: in the future could you enable “allow edits by maintainers” in your PRs? It makes it easier for us to fix these type of things.

**Comment by gorazdko** [comment]
CI was fixed automatically. So no issues now.

I had asked Wolf to manually reset the CI but said that the error persisted, so i wasn't sure what was wrong.

**Pull request merged**
