### PR TITLE
Fixed unit tests by removing `birthdate` field in seed URs.

### PR DESCRIPTION
**Pull request by wolfmcnally**
* Removed `birthdate` field from generated `ur:crypto-seed` URs, which was causing unit tests to become invalid. A specific flag to set the `birthdate` field could be added at a later date.
* Bumped version number to 0.9.1

### CODE REVIEW

**Comment by ChristopherA** [comment]
Part of the reason why I liked the `birthdate` field in some tests was to make sure that if there was data beyond the crypto-seed and the reader didn't know what it was, it would properly ignore it. 

Are there still unit tests that still include testing that?

**Comment by gorazdko** [comment]
Builds and runs on Linux.

> Are there still unit tests that still include testing that?

No, this PR completely disables the birthdate generation. 

@wolfmcnally please consider reviewing the PR you're building on top of https://github.com/BlockchainCommons/bc-seedtool-cli/pull/37#issuecomment-706590147 first

**Comment by wolfmcnally** [comment]
> Part of the reason why I liked the `birthdate` field in some tests was to make sure that if there was data beyond the crypto-seed and the reader didn't know what it was, it would properly ignore it.
> 
> Are there still unit tests that still include testing that?

The unit tests *never* tested the birthdate feature. But I did *not* remove the birthdate field from the CBOR, I simply don't set it now. The problem was that the birthdate field was being set from the system clock, which means that the generated URs weren't truly deterministic. If we want to fully support birthdate in the future, we will simply add a flag that allows either setting the birthdate CBOR field from the system clock *or* by providing its value on the command line.

**Comment by wolfmcnally** [comment]
> Builds and runs on Linux.
> 
> > Are there still unit tests that still include testing that?
> 
> No, this PR completely disables the birthdate generation.
> 
> @wolfmcnally please consider reviewing the PR you're building on top of [#37 (comment)](https://github.com/BlockchainCommons/bc-seedtool-cli/pull/37#issuecomment-706590147) first

OK, that's merged. See review comment.

**Comment by wolfmcnally** [comment]
@gorazdko OK, thank you. That's merged and tested. @ChristopherA ready for review.

**Comment by gorazdko** [comment]
ACK, builds and runs on windows and linux

**Review by ChristopherA — APPROVED** [review]
Tested ACK: Built on macOS Catalina (10.15.6), using command line tools for Xcode 11.7. Tested via `.build.sh` builds with no errors, did `sudo make install`. Did `git clean -n -ffdx` to test that `make distclean` did its job. Did not test incremental build or other platforms. As this fixes a critical bug PR is approved for Master branch.

**Pull request merged**
